spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: exemple
      database: hexagonal

enderecoapi:
 client:
   address:
     url: http://localhost:8082/addresses


